### ISSUE TITLE
Font awesome icons on the webpage are broken

### ISSUE THREAD

**Issue by okuramasafumi** [litaio/lita.io#20]
Hi, I noticed that on the main web page (https://www.lita.io/) font awesome icons are not displayed.
I tried to reproduce it with `middleman server` command but I couldn't.
I found some errors like:
```
fontawesome-webfont-638c652d.woff2:1 Failed to load resource: the server responded with a status of 404 ()
fontawesome-webfont-4a313eb9.woff:1 Failed to load resource: the server responded with a status of 404 ()
fontawesome-webfont-6484f1af.ttf:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by jimmycuadra** [comment]
I noticed this too but haven't gotten to fixing it yet. Thanks for the report!

**Comment by jimmycuadra** [comment]
This was actually easier than I expected to fix. It's done now. Thanks again.
